### ISSUE TITLE
License and Contribution

### ISSUE THREAD

**Issue by ponte-vecchio** [anufrievroman/Angry-Reviewer#2]
G'day,

First of all, I am absolutely in love with AR.

As a person in academia myself, I would like to fork the repo and contribute upstream. That being said, I wanted to clarify the state of licensing. As it stands, the repo's rights are reserved to you since there is no dedicated `LICENSE` file. Which raises some questions before I go ahead with the fork:

1. Are you open to contributions at this time?
2. What is the license of the project?
3. If the answer to **1** is **Yes** but the answer to **2** is **All rights reserved**, would you be open to contributions with due credit (insofar as legality is concerned)?

Cheers in advance, happy AngryReviewing.

**Comment by anufrievroman** [comment]
Hello, thank you for opening the issue. Indeed, I forgot to drop license in this repo (I updated now). I use GPL license for all AR repos (this one and extensions). So, to answer your questions.

1. I am open to contributions, so you are welcome to contribute!
2. GPL
3. If you contribute, you will appear in github repo as a contributor, like for example [here](https://github.com/anufrievroman/vim-angry-reviewer). If the contribution is very large, I can also mention you on the website. However, before coding very big contributions, it might be better to discuss.

Thank you for your interest in the project.

**Comment by ponte-vecchio** [comment]
Thank you for the prompt response!
