### ISSUE TITLE
Plugin for Obsidian

### ISSUE THREAD

**Issue by simonpacis** [anufrievroman/Angry-Reviewer#4]
Hi,

I wasn't sure what the best way to reach you was, but I have developed an AngryReviewer.com plugin for [Obsidian](https://obsidian.md): [https://github.com/simonpacis/obsidian-angry-reviewer](https://github.com/simonpacis/obsidian-angry-reviewer).

It stores a portable version of processing.py and rules.py, like the Vim plugin.

Please let me know if this is alright.

Best,
Simon Pacis

**Comment by anufrievroman** [comment]
Hi, that is awesome!
I never tried Odsidian myself, but I'll install it on this occasion.
Thank you, I added the link to your plugin on the website.

**Comment by anufrievroman** [comment]
I checked, it works for me :)
Besides, maybe we can use a more minimal icon to better fit the Obsidian's side panel. Something like that:

![icon_mini](https://user-images.githubusercontent.com/42904990/227750343-16907227-e7bd-490b-a3cd-ce3ca19c61d4.svg)

**Comment by simonpacis** [comment]
Perfect, I'm glad it works! And thank you for the icon; I agree this would be better. I will also make some other improvements, including the American/British selector.
